"use client";
import { useState, useTransition } from "react";
import type { Goal, Media, Month } from "@/lib/types";
import { Save, Upload } from "lucide-react";

type Props = { settings: Record<string, string>; months: Month[]; goals: Goal[]; media: Media[] };

export function AdminClient({ settings, months, goals }: Props) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState("");
  async function postJson(url: string, payload: unknown, success: string) {
    startTransition(async () => { const res = await fetch(url, { method: "POST", body: JSON.stringify(payload) }); setMessage(res.ok ? success : "خطا رخ داد."); });
  }
  async function saveSettings(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); postJson("/api/settings", Object.fromEntries(new FormData(e.currentTarget).entries()), "تنظیمات ذخیره شد."); }
  async function saveMonth(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); postJson("/api/months", { id: data.id, month_title: data.month_title, income: Number(data.income || 0), expense: Number(data.expense || 0), investment: Number(data.investment || 0), note: data.note }, "ماه ذخیره شد."); }
  async function saveGoal(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); postJson("/api/goals/toggle", { id: data.id, title: data.title, current_amount: Number(data.current_amount || 0), target_amount: Number(data.target_amount || 0), mode: "edit" }, "هدف ذخیره شد."); }
  async function upload(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); startTransition(async () => { const res = await fetch("/api/media/upload", { method: "POST", body: form }); setMessage(res.ok ? "فایل آپلود شد. صفحه را رفرش کن." : "خطا در آپلود فایل."); }); }
  async function uploadSong(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); startTransition(async () => { const res = await fetch("/api/media/upload", { method: "POST", body: form }); setMessage(res.ok ? "آهنگ آپلود شد. صفحه را رفرش کن." : "خطا در آپلود آهنگ."); }); }

  return <div className="mx-auto grid max-w-[1360px] gap-5 p-4 md:p-7"><section className="luxe-card p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-black text-gold">Admin Panel</p><h1 className="mt-2 text-4xl font-black">تنظیمات کامل سایت</h1><p className="mt-3 text-sm font-bold text-stone-500">عنوان‌ها، مبالغ، ماه‌ها، عکس‌ها و آهنگ‌ها از اینجا مدیریت می‌شوند.</p></div><a href="/" className="luxe-button-soft">بازگشت به صفحه اصلی</a></div>{message && <div className="mt-5 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-700">{message}</div>}</section>
  <section className="luxe-card p-6"><h2 className="mb-5 text-2xl font-black">تنظیمات کلی</h2><form onSubmit={saveSettings} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field name="site_title" label="عنوان سایت" defaultValue={settings.site_title}/><Field name="site_tagline" label="زیرعنوان" defaultValue={settings.site_tagline}/><Field name="hero_quote" label="متن هدر" defaultValue={settings.hero_quote}/><Field name="starting_cash" label="پول نقد شروع" defaultValue={settings.starting_cash} type="number"/><Field name="car_goal" label="هدف خودرو" defaultValue={settings.car_goal} type="number"/><Field name="trip_goal" label="هدف سفر" defaultValue={settings.trip_goal} type="number"/><Field name="fun_goal" label="هدف خوش‌گذرانی" defaultValue={settings.fun_goal} type="number"/><Field name="invest_goal" label="هدف سرمایه‌گذاری" defaultValue={settings.invest_goal} type="number"/><button disabled={pending} className="luxe-button md:col-span-2 xl:col-span-4"><Save className="ml-2 inline h-4 w-4"/>ذخیره تنظیمات</button></form></section>
  <section className="luxe-card p-6"><h2 className="mb-5 text-2xl font-black">عکس‌های دونفره</h2><form onSubmit={upload} className="grid gap-4 md:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="type" value="couple_photo"/><input className="luxe-input" type="file" name="file" accept="image/*" required/><input className="luxe-input" name="caption" placeholder="کپشن اختیاری"/><button disabled={pending} className="luxe-button"><Upload className="ml-2 inline h-4 w-4"/>آپلود</button></form></section>
  <section className="luxe-card p-6"><h2 className="mb-5 text-2xl font-black">هدف‌ها</h2><div className="grid gap-4">{goals.map((g) => <form key={g.id} onSubmit={saveGoal} className="grid gap-4 md:grid-cols-4"><input type="hidden" name="id" value={g.id}/><Field name="title" label="عنوان هدف" defaultValue={g.title}/><Field name="current_amount" label="مقدار فعلی" defaultValue={String(g.current_amount)} type="number"/><Field name="target_amount" label="مقدار هدف" defaultValue={String(g.target_amount)} type="number"/><button className="luxe-button">ذخیره هدف</button></form>)}</div></section>
  <section className="grid gap-5"><h2 className="px-2 text-2xl font-black">ماه‌ها</h2>{months.map((month) => <div key={month.id} className="luxe-card p-6"><form onSubmit={saveMonth} className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><input type="hidden" name="id" value={month.id}/><Field name="month_title" label="عنوان ماه" defaultValue={month.month_title}/><Field name="income" label="درآمد" defaultValue={String(month.income)} type="number"/><Field name="expense" label="خرج" defaultValue={String(month.expense)} type="number"/><Field name="investment" label="سرمایه‌گذاری" defaultValue={String(month.investment)} type="number"/><Field name="note" label="یادداشت" defaultValue={month.note}/><button className="luxe-button xl:col-span-5">ذخیره {month.month_title}</button></form><div className="mt-5 grid gap-4 md:grid-cols-2"><form onSubmit={upload} className="grid gap-3 rounded-3xl border border-stone-200 bg-white/60 p-4"><input type="hidden" name="type" value="month_photo"/><input type="hidden" name="month_id" value={month.id}/><label className="font-black">افزودن عکس ماه</label><input className="luxe-input" type="file" name="file" accept="image/*" required/><input className="luxe-input" name="caption" placeholder="کپشن"/><button className="luxe-button">آپلود عکس</button></form><form onSubmit={uploadSong} className="grid gap-3 rounded-3xl border border-stone-200 bg-white/60 p-4"><input type="hidden" name="type" value="month_song"/><input type="hidden" name="month_id" value={month.id}/><label className="font-black">آپلود آهنگ ماه</label><input className="luxe-input" type="file" name="file" accept="audio/*" required/><button className="luxe-button">آپلود آهنگ</button></form></div></div>)}</section></div>;
}
function Field({ name, label, defaultValue, type = "text" }: { name: string; label: string; defaultValue?: string; type?: string }) { return <label className="grid gap-2 text-sm font-black text-stone-600">{label}<input className="luxe-input" name={name} type={type} defaultValue={defaultValue || ""}/></label>; }
